"""Informe HTML autocontenido con contenido escapado para evitar inyección."""
import html
from pathlib import Path
from .engine import Result

def write_html(result: Result, output: Path) -> None:
    esc = lambda value: html.escape(str(value), quote=True)
    errors = sum(item.severity == "error" for item in result.findings)
    warnings = sum(item.severity == "warning" for item in result.findings)
    columns = []
    for col in result.columns:
        cls = "ok" if col.completeness >= 95 else "warn"
        columns.append(f"<tr><td><b>{esc(col.name)}</b></td><td>{esc(col.inferred_type)}</td><td>{col.rows:,}</td><td>{col.distinct:,}</td><td><span class='meter {cls}'><i style='width:{col.completeness}%'></i></span>{col.completeness}%</td><td>{esc(col.minimum or '—')}</td><td>{esc(col.maximum or '—')}</td></tr>")
    findings = []
    for item in sorted(result.findings, key=lambda entry: entry.severity != "error"):
        severity = "Error" if item.severity == "error" else "Aviso"
        lines = ", ".join(map(str, item.example_lines)) or "—"
        findings.append(f"<tr><td><span class='tag {'bad' if item.severity == 'error' else 'caution'}'>{severity}</span></td><td><b>{esc(item.title)}</b><small>{esc(item.code)} · {esc(item.column or 'archivo')}</small></td><td>{esc(item.message)}</td><td>{item.affected_rows:,}</td><td>{esc(lines)}</td></tr>")
    if not findings:
        findings.append("<tr><td colspan='5' class='empty'>Sin hallazgos: el archivo cumple con el contrato de calidad.</td></tr>")
    state = "Aprobado" if result.passed else "Bloqueado"
    state_class = "good" if result.passed else "bad"
    page = f"""<!doctype html><html lang='es'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Calidad de datos · {esc(result.source)}</title><style>
:root{{--navy:#142d40;--teal:#137c72;--mint:#e4f5ef;--ink:#1c2e3b;--muted:#677b89;--line:#e4ebee;--bg:#f3f7f8;--red:#a52c3b;--amber:#925b00}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 Inter,system-ui,-apple-system,'Segoe UI',sans-serif}}header{{background:linear-gradient(120deg,#11283b,#145359);color:white;padding:38px max(22px,calc((100vw - 1120px)/2))}}.brand{{font-size:13px;letter-spacing:.13em;font-weight:800}}.mark{{background:#55d2b0;color:#063f40;border-radius:9px;padding:7px 9px;margin-right:10px}}h1{{font-size:clamp(27px,4vw,39px);line-height:1.12;margin:30px 0 8px}}header p{{color:#c9dbe1;margin:0}}main{{max-width:1120px;margin:26px auto;padding:0 22px 42px}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}}.card,.panel{{background:white;border:1px solid var(--line);border-radius:15px;box-shadow:0 7px 22px #142d4008}}.card{{padding:18px}}.label{{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);font-weight:750}}.metric{{font-size:29px;font-weight:800;margin:8px 0 2px}}.sub,small{{font-size:12px;color:var(--muted)}}.tag{{display:inline-block;border-radius:20px;padding:5px 10px;font-size:12px;font-weight:800}}.tag.good{{background:var(--mint);color:#08725e}}.tag.bad{{background:#ffeaed;color:var(--red)}}.tag.caution{{background:#fff2d8;color:var(--amber)}}.panel{{margin-top:17px;padding:21px}}h2{{font-size:18px;margin:0 0 14px}}.scroll{{overflow-x:auto}}table{{width:100%;border-collapse:collapse;min-width:680px}}th{{font-size:11px;text-align:left;color:var(--muted);text-transform:uppercase;letter-spacing:.07em;border-bottom:1px solid var(--line);padding:10px}}td{{padding:12px 10px;border-bottom:1px solid #edf1f3;vertical-align:top}}tbody tr:last-child td{{border:0}}small{{display:block;margin-top:3px}}.meter{{display:inline-block;width:90px;height:7px;background:#e7edef;border-radius:9px;overflow:hidden;vertical-align:middle;margin-right:8px}}.meter i{{display:block;height:100%;background:var(--teal)}}.meter.warn i{{background:#e2a23d}}.empty{{text-align:center;color:var(--teal);padding:24px}}footer{{color:var(--muted);font-size:12px;margin:18px 2px}}@media(max-width:700px){{header{{padding:28px 18px}}main{{padding:0 12px 30px}}.grid{{grid-template-columns:repeat(2,1fr);gap:8px}}.card{{padding:14px}}.metric{{font-size:23px}}.panel{{padding:15px}}}}
</style></head><body><header><div class='brand'><span class='mark'>QG</span>DATA QUALITY GATE</div><h1>Calidad de datos, antes de producción.</h1><p>{esc(result.source)} · Contrato: {esc(result.contract)}</p></header><main><section class='grid'><div class='card'><div class='label'>Resultado</div><div class='metric'><span class='tag {state_class}'>{state}</span></div><div class='sub'>{result.row_count:,} filas · {result.column_count} columnas</div></div><div class='card'><div class='label'>Puntuación</div><div class='metric'>{result.score:.1f}<span class='sub'> / 100</span></div><div class='sub'>Calculada según hallazgos y severidad</div></div><div class='card'><div class='label'>Errores</div><div class='metric'>{errors}</div><div class='sub'>Incumplimientos que bloquean</div></div><div class='card'><div class='label'>Advertencias</div><div class='metric'>{warnings}</div><div class='sub'>Requieren revisión</div></div></section><section class='panel'><h2>Perfil por columna</h2><div class='scroll'><table><thead><tr><th>Columna</th><th>Tipo detectado</th><th>Filas</th><th>Distintos</th><th>Completitud</th><th>Mínimo</th><th>Máximo</th></tr></thead><tbody>{''.join(columns)}</tbody></table></div></section><section class='panel'><h2>Hallazgos <span class='sub'>({len(result.findings)})</span></h2><div class='scroll'><table><thead><tr><th>Nivel</th><th>Regla</th><th>Detalle</th><th>Filas afectadas</th><th>Líneas de ejemplo</th></tr></thead><tbody>{''.join(findings)}</tbody></table></div></section><footer>Generado por Data Quality Gate · {esc(result.generated_at)}</footer></main></body></html>"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(page, encoding="utf-8")
